[package]
name = "genetica"
version = "1.0.0"
edition = "2024"
description = "A crate that helps with creating genetic algorithms"
readme = "README.md"
repository = "https://github.com/darrkenn/genetica"
license = "MIT"

[dependencies]
rand = "0.9.2"
